export const config={runtime:"edge"};
const records=[
{id:"ob-ayahuasca",title:"Ayahuasca discussion removed, then ordered restored",platform:"Instagram",recordType:"Oversight decision",status:"confirmed-error",date:"2021-12-09",claim:"Meta removed a post discussing traditional ayahuasca use; the Oversight Board found it did not violate the rules as articulated at the time and directed restoration.",establishes:"A documented erroneous removal in this specific case.",boundary:"It does not establish a platform-wide motive or quantify prevalence.",source:"Meta Oversight Board",sourceUrl:"https://www.oversightboard.com/news/1780492362340442-oversight-board-overturns-meta-s-decision-case-2021-013-ig-ua/",verifiedOn:"2026-08-16"},
{id:"ob-ketamine",title:"Ketamine branded-content enforcement found inconsistent",platform:"Instagram",recordType:"Oversight decision",status:"official-record",date:"2023-08-17",claim:"The Oversight Board identified inconsistent application of Meta policies to a paid post promoting ketamine treatment.",establishes:"A documented policy-enforcement inconsistency in the reviewed case.",boundary:"The decision concerns branded content and restricted-goods rules; it is not a general endorsement of ketamine marketing.",source:"Meta Oversight Board",sourceUrl:"https://www.oversightboard.com/decision/ig-tom6ixvh-22/",verifiedOn:"2026-08-16"},
{id:"congress-drugads",title:"Bipartisan lawmakers questioned illicit-drug ads on Meta",platform:"Meta",recordType:"Government record",status:"official-record",date:"2024-08-15",claim:"Nineteen U.S. House members asked Meta to explain how illicit-drug advertisements appeared on Facebook and Instagram.",establishes:"Official congressional scrutiny of Meta ad enforcement.",boundary:"The letter concerns illicit sales; it does not itself prove collateral suppression of lawful educators.",source:"Office of Rep. Tim Walberg",sourceUrl:"https://walberg.house.gov/media/press-releases/walberg-bilirakis-castor-and-trahan-led-bipartisan-letter-calls-meta-crack-down",verifiedOn:"2026-08-16"},
{id:"meta-spam",title:"Meta describes reach reductions for spam and unoriginal content",platform:"Facebook",recordType:"Platform policy",status:"official-policy",date:"2025-04-24",claim:"Meta states that accounts using spam tactics or repeatedly reusing content may receive reduced reach or lose monetization.",establishes:"Meta’s stated distribution policy and some disclosed enforcement categories.",boundary:"A reach decline requires account-level diagnostics; the policy does not explain every decline.",source:"Meta Newsroom",sourceUrl:"https://about.fb.com/news/2025/04/cracking-down-spammy-content-facebook/",verifiedOn:"2026-08-16"},
{id:"pmp-wave",title:"Psychedelic organizations reported a May 2025 suspension wave",platform:"Instagram",recordType:"Reported incident",status:"reported",date:"2025-05-30",claim:"Plant Media Project and affected organizations reported multiple suspensions and vague notices during a concentrated period.",establishes:"A first-party/coalition report suitable for incident intake and corroboration.",boundary:"Counts, common cause, policy basis, and platform intent require independent records or Meta confirmation.",source:"Students for Sensible Drug Policy",sourceUrl:"https://ssdp.org/blog/stop-meta-censorship/",verifiedOn:"2026-08-16"}
];
export default function handler(req){if(req.method!=="GET")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:{"content-type":"application/json","allow":"GET"}});return new Response(JSON.stringify({records,total:records.length,verifiedOn:"2026-08-16",methodology:"primary or first-party sources; claim boundaries preserved"}),{headers:{"content-type":"application/json","cache-control":"public, s-maxage=86400, stale-while-revalidate=604800"}})}
